### PR TITLE
To Do List structure

### PR DESCRIPTION
**Pull request by Aliahmad-karimi**
## Steps to the exercise

- Set the Linters
- Set the webPack for the repo
- Give the Html structure
- Set styles for the form
- Set the Js for the form

### CODE REVIEW

**Review by Bondok6 — COMMENTED** [review]
## Hi @Aliahmad-karimi 🙋‍♂️, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Your `README` file should be descriptive - all main headers from the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) should be present 👌
 Please, update it 💯
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Davidosky007 — COMMENTED** [review]
Hi @Aliahmad-karimi 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive readme file, kindly use this [readme template](https://github.com/microverseinc/readme-template) and customize it to suit your project 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by prolajumokeoni** [comment]
Hi @Aliahmad-karimi kindly take out time to effect the requested changes, a professional  readme is an important requirement you need to do to get your project reviewed, 

- [x] Please document your project professionally, Your readme file should be descriptive all main headers from the [microverse README template](https://github.com/microverseinc/readme-template/blob/master/README.md) should be present in your repo 👍🏿

**Comment by Aliahmad-karimi** [comment]
Dear @prolajumokeoni 
Thanks for the suggestion. I got it but forgot to do it in my branch also, so please recheck my request

**Comment by prolajumokeoni** [comment]
> Dear @prolajumokeoni Thanks for the suggestion. I got it but forgot to do it in my branch also, so please recheck my request

Good job 👍🏿

**Review by prolajumokeoni — APPROVED** [review]
Hi @Aliahmad-karimi 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
